# -*- Makefile -*-

# Set the name of the project here
PROJECT_NAME := KLEE
PROJ_VERSION := 1.1.0

# Set this variable to the top of the LLVM source tree.
LLVM_SRC_ROOT = /usr/lib/llvm-3.4/build

# Set this variable to the top level directory where LLVM was built
# (this is *not* the same as OBJ_ROOT as defined in LLVM's Makefile.config).
LLVM_OBJ_ROOT = /usr/lib/llvm-3.4/build

LLVM_VERSION_MAJOR = 3
LLVM_VERSION_MINOR = 4

# Set this to the build mode used to build LLVM (not necessarily the same
# as the build mode used for KLEE)
LLVM_BUILD_MODE = Release

# Set the directory root of this project's source files
PROJ_SRC_ROOT := $(subst //,/,/home/tannguyen/Dropbox/NUS/Test_Merge/TracerX_Taint)

# Set the root directory of this project's object files
PROJ_OBJ_ROOT := $(subst //,/,/home/tannguyen/Dropbox/NUS/Test_Merge/TracerX_Taint)

# Set the root directory of this project's install prefix
PROJ_INSTALL_ROOT := /usr/local

KLEE_USE_CXX11 := 0

STP_CFLAGS := -I/home/tannguyen/stp/build/include
STP_LDFLAGS := -L/home/tannguyen/stp/build/lib -lstp -lminisat

Z3_CFLAGS := -I/home/tannguyen/z3/include
Z3_LDFLAGS := -L/home/tannguyen/z3/lib -lz3

ENABLE_METASMT := 0
METASMT_ROOT := 

ENABLE_POSIX_RUNTIME := 1
ENABLE_UCLIBC := 1

KLEE_UCLIBC_BCA := /home/tannguyen/klee-uclibc/lib/libc.a

HAVE_SELINUX := 0

RUNTIME_ENABLE_OPTIMIZED := 1
RUNTIME_DISABLE_ASSERTIONS := 0
RUNTIME_DEBUG_SYMBOLS := 
RUNTIME_ENABLE_COVERAGE :=
RUNTIME_ENABLE_PROFILING :=

# Compilers used to build runtime library and run tests
KLEE_BITCODE_C_COMPILER := /usr/lib/llvm-3.4/build/Release/bin/clang
KLEE_BITCODE_CXX_COMPILER := /usr/lib/llvm-3.4/build/Release/bin/clang++

# Host compiler
KLEE_HOST_C_COMPILER := gcc
KLEE_HOST_CXX_COMPILER := g++

# A list of "features" which tests can check for in XFAIL:
TEST_FEATURE_LIST :=

ifeq ($(HAVE_SELINUX_SELINUX_H),1)
  TEST_FEATURE_LIST += have-selinux
else
  TEST_FEATURE_LIST += no-selinux
endif

# disable unwind test
TEST_FEATURE_LIST += no-unwind

CFLAGS := -g -O2 -Wall -g
CXXFLAGS := -g -O2 -g -Wall
LDFLAGS :=  -g

REQUIRES_RTTI := 0
